const nodemailer = require('nodemailer');

async function sendBookingEmail(booking, functionSheetPdf, kitchenPrepPdf) {
  const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.EMAIL_PORT || '587'),
    secure: false,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const mailOptions = {
    from: `"Bash Events Bookings" <${process.env.EMAIL_USER}>`,
    to: 'info@bashevents.co.uk',
    subject: `NEW BOOKING: ${booking.menuTitle} — ${booking.guestCount} guests — ${booking.eventDate} — Ref: ${booking.bookingRef}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2 style="color: #FF6B2B;">New Booking Confirmed!</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Ref</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.bookingRef}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Client</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.customerName}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Email</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.customerEmail}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Phone</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.customerPhone || 'N/A'}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Date</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.eventDate}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Event</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.eventType}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Location</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.location}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Guests</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.guestCount}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Menu</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.menuTitle} — ${booking.packageName}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Total</td><td style="padding: 8px; border-bottom: 1px solid #eee; font-size: 18px; font-weight: bold;">£${booking.subtotal.toLocaleString()}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Deposit Paid</td><td style="padding: 8px; border-bottom: 1px solid #eee; color: #00D68F;">£${booking.depositAmount}</td></tr>
          <tr><td style="padding: 8px; font-weight: bold;">Balance Due</td><td style="padding: 8px;">£${booking.balanceDue}</td></tr>
        </table>
        ${booking.notes ? `<p style="margin-top: 16px;"><strong>Notes:</strong> ${booking.notes}</p>` : ''}
        <p style="margin-top: 24px; color: #777; font-size: 12px;">Function sheet and kitchen prep sheet attached. Generated by Bash Events Booking System.</p>
      </div>
    `,
    attachments: [
      {
        filename: `FunctionSheet-${booking.bookingRef}.pdf`,
        content: functionSheetPdf,
        contentType: 'application/pdf',
      },
      {
        filename: `KitchenPrep-${booking.bookingRef}.pdf`,
        content: kitchenPrepPdf,
        contentType: 'application/pdf',
      },
    ],
  };

  // Also send confirmation to the customer
  const customerMail = {
    from: `"Bash Events" <${process.env.EMAIL_USER}>`,
    to: booking.customerEmail,
    subject: `Booking Confirmed — ${booking.menuTitle} — Ref: ${booking.bookingRef}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2 style="color: #FF6B2B;">Thank You, ${booking.customerName}!</h2>
        <p>Your booking with Bash Events has been confirmed. Here are your details:</p>
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Booking Ref</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.bookingRef}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Event Date</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.eventDate}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Menu</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.menuTitle} — ${booking.packageName}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Guests</td><td style="padding: 8px; border-bottom: 1px solid #eee;">${booking.guestCount}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Total</td><td style="padding: 8px; border-bottom: 1px solid #eee;">£${booking.subtotal.toLocaleString()}</td></tr>
          <tr><td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Deposit Paid</td><td style="padding: 8px; border-bottom: 1px solid #eee; color: #00D68F;">£${booking.depositAmount}</td></tr>
          <tr><td style="padding: 8px; font-weight: bold;">Balance Due</td><td style="padding: 8px;">£${booking.balanceDue} (due 7 days before event)</td></tr>
        </table>
        <p style="margin-top: 16px;">We'll be in touch closer to your event date to finalise the details.</p>
        <p>If you have any questions, reply to this email or call us.</p>
        <p style="margin-top: 24px; color: #777;">Bash Events — Premium Event & Street Food Catering<br>London & Essex | info@bashevents.co.uk</p>
      </div>
    `,
    attachments: [
      {
        filename: `FunctionSheet-${booking.bookingRef}.pdf`,
        content: functionSheetPdf,
        contentType: 'application/pdf',
      },
    ],
  };

  await Promise.all([
    transporter.sendMail(mailOptions),
    transporter.sendMail(customerMail),
  ]);
}

module.exports = { sendBookingEmail };
